server:
  port: 8082
spring:
  application:
    name: spring-msg-consumer2
  cloud:
    stream:
      bindings:
        myJebLinInput:
          group: groupB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/