server:
  port: 8083
spring:
  application:
    name: spring-msg-consumer3
  cloud:
    stream:
      bindings:
        myJebLinInput:
          group: groupB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/