server:
  port: 8081
spring:
  application:
    name: spring-msg-consumer
  cloud:
    stream:
      bindings:
        myJebLinInput:
          group: groupA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/