server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # registerWithEureka表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetch-registry: false # fetchRegistry表示是否从eureka服务器获取注册信息，同上，这里不需要。
