spring:
  application:
    name: ek-provider
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: JebLinCompany
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #  注册的服务端的地址
logging:
  level:
    com.netflix: DEBUG